// Mock Strategy Data for Automated Trading

export interface Strategy {
  id: string;
  name: string;
  type: 'Grid' | 'DCA' | 'Trend' | 'Custom' | 'Arbitrage' | 'Rebalancing';
  marketPair: string;
  riskLevel: 'Low' | 'Medium' | 'High';
  pnl30d: number;
  pnlUSD: number;
  drawdown30d: number;
  roi: number;
  description: string;
  creator: string;
  creatorAvatar?: string;
  followers: number;
  isVerified: boolean;
  isMyStrategy?: boolean;
  runtime?: string;
  minInvestment?: number;
  trades24h?: number;
  totalTrades?: number;
  sharpeRatio?: number;
  aum?: number; // Assets Under Management
  performanceData?: number[]; // For chart
  direction?: 'Long' | 'Short' | 'Neutral';
  leverage?: number;
  status?: 'active' | 'paused' | 'stopped';
}

// My Strategies (User's own strategies)
export const mockMyStrategies: Strategy[] = [
  {
    id: 'my-1',
    name: 'ETH Grid Bot',
    type: 'Grid',
    marketPair: 'ETH/USDT',
    riskLevel: 'Low',
    pnl30d: 12.5,
    pnlUSD: 1250.50,
    drawdown30d: 2.3,
    roi: 12.5,
    description: 'Automated grid trading strategy for ETH/USDT pair',
    creator: 'You',
    followers: 0,
    isVerified: true,
    isMyStrategy: true,
    runtime: '15d 8h',
    minInvestment: 1000,
    trades24h: 45,
    totalTrades: 1234,
    sharpeRatio: 2.8,
    aum: 10000,
    performanceData: [0, 2.5, 5.1, 7.8, 9.2, 11.5, 12.5],
    direction: 'Neutral',
    leverage: 1,
    status: 'active',
  },
  {
    id: 'my-2',
    name: 'BTC DCA Accumulator',
    type: 'DCA',
    marketPair: 'BTC/USDT',
    riskLevel: 'Medium',
    pnl30d: 8.2,
    pnlUSD: 820.00,
    drawdown30d: 5.1,
    roi: 8.2,
    description: 'Dollar-cost averaging strategy for BTC accumulation',
    creator: 'You',
    followers: 0,
    isVerified: true,
    isMyStrategy: true,
    runtime: '22d 14h',
    minInvestment: 500,
    trades24h: 12,
    totalTrades: 456,
    sharpeRatio: 2.1,
    aum: 10000,
    performanceData: [0, 1.2, 3.5, 5.8, 7.1, 8.0, 8.2],
    direction: 'Long',
    leverage: 1,
    status: 'active',
  },
  {
    id: 'my-3',
    name: 'SOL Trend Follower',
    type: 'Trend',
    marketPair: 'SOL/USDT',
    riskLevel: 'High',
    pnl30d: 18.7,
    pnlUSD: 1870.00,
    drawdown30d: 8.9,
    roi: 18.7,
    description: 'Advanced trend-following strategy with dynamic stop-loss',
    creator: 'You',
    followers: 0,
    isVerified: false,
    isMyStrategy: true,
    runtime: '8d 3h',
    minInvestment: 2000,
    trades24h: 8,
    totalTrades: 89,
    sharpeRatio: 3.2,
    aum: 10000,
    performanceData: [0, 5.2, 10.1, 14.8, 16.5, 17.9, 18.7],
    direction: 'Long',
    leverage: 3,
    status: 'paused',
  },
];

// Marketplace Strategies (Community strategies)
export const mockMarketplaceStrategies: Strategy[] = [
  {
    id: '1',
    name: 'ETH Grid Bot Pro',
    type: 'Grid',
    marketPair: 'ETH/USDT',
    riskLevel: 'Low',
    pnl30d: 34.91,
    pnlUSD: 3491.81,
    drawdown30d: 15.99,
    roi: 34.91,
    description: 'Professional grid trading strategy for ETH/USDT pair',
    creator: 'ProTrader',
    creatorAvatar: 'PT',
    followers: 1247,
    isVerified: true,
    isMyStrategy: false,
    runtime: '3d 11h',
    minInvestment: 889.74,
    trades24h: 415,
    totalTrades: 3519,
    sharpeRatio: 3.38,
    aum: 8348967.72,
    performanceData: [0, 5.2, 12.5, 20.1, 28.5, 32.1, 34.91],
    direction: 'Short',
    leverage: 5,
    status: 'active',
  },
  {
    id: '2',
    name: 'DASH Neutral Grid',
    type: 'Grid',
    marketPair: 'DASH/USDT',
    riskLevel: 'Low',
    pnl30d: 5.27,
    pnlUSD: 2637.71,
    drawdown30d: 1.26,
    roi: 5.27,
    description: 'Neutral grid strategy with trailing stop',
    creator: 'GridMaster',
    creatorAvatar: 'GM',
    followers: 892,
    isVerified: true,
    isMyStrategy: false,
    runtime: '6d 6h',
    minInvestment: 645.60,
    trades24h: 213,
    totalTrades: 578,
    sharpeRatio: 3.40,
    aum: 864395.14,
    performanceData: [0, 1.2, 2.5, 3.8, 4.5, 5.0, 5.27],
    direction: 'Neutral',
    leverage: 5,
    status: 'active',
  },
  {
    id: '3',
    name: 'LIT Short Grid',
    type: 'Grid',
    marketPair: 'LIT/USDT',
    riskLevel: 'Medium',
    pnl30d: 11.20,
    pnlUSD: 2240.71,
    drawdown30d: 5.17,
    roi: 11.20,
    description: 'Short grid strategy optimized for LIT volatility',
    creator: 'ShortKing',
    creatorAvatar: 'SK',
    followers: 2156,
    isVerified: true,
    isMyStrategy: false,
    runtime: '3d 20h',
    minInvestment: 174.44,
    trades24h: 52,
    totalTrades: 641,
    sharpeRatio: 2.9,
    aum: 124601.83,
    performanceData: [0, 2.1, 5.5, 8.2, 9.8, 10.5, 11.20],
    direction: 'Short',
    leverage: 5,
    status: 'active',
  },
  {
    id: '4',
    name: 'ETH Long Futures',
    type: 'Trend',
    marketPair: 'ETH/USDC',
    riskLevel: 'Medium',
    pnl30d: 2.87,
    pnlUSD: 1750.19,
    drawdown30d: 4.89,
    roi: 2.87,
    description: 'Long futures strategy with trailing stop',
    creator: 'FuturesPro',
    creatorAvatar: 'FP',
    followers: 634,
    isVerified: true,
    isMyStrategy: false,
    runtime: '6d 9h',
    minInvestment: 619.82,
    trades24h: 18,
    totalTrades: 716,
    sharpeRatio: 2.5,
    aum: 289456.12,
    performanceData: [0, 0.5, 1.2, 2.0, 2.5, 2.8, 2.87],
    direction: 'Long',
    leverage: 8,
    status: 'active',
  },
  {
    id: '5',
    name: 'SOL Long Grid',
    type: 'Grid',
    marketPair: 'SOL/USDT',
    riskLevel: 'Medium',
    pnl30d: 7.90,
    pnlUSD: 1580.60,
    drawdown30d: 8.34,
    roi: 7.90,
    description: 'Long grid strategy for SOL',
    creator: 'SolanaPro',
    creatorAvatar: 'SP',
    followers: 456,
    isVerified: true,
    isMyStrategy: false,
    runtime: '4d 17h',
    minInvestment: 20.38,
    trades24h: 8,
    totalTrades: 90,
    sharpeRatio: 2.2,
    aum: 20000.00,
    performanceData: [0, 1.5, 3.2, 5.5, 6.8, 7.5, 7.90],
    direction: 'Long',
    leverage: 8,
    status: 'active',
  },
  {
    id: '6',
    name: 'BTC DCA Accumulator',
    type: 'DCA',
    marketPair: 'BTC/USDT',
    riskLevel: 'Medium',
    pnl30d: 8.2,
    pnlUSD: 820.00,
    drawdown30d: 5.1,
    roi: 8.2,
    description: 'Dollar-cost averaging strategy for BTC accumulation',
    creator: 'CryptoQuant',
    creatorAvatar: 'CQ',
    followers: 892,
    isVerified: true,
    isMyStrategy: false,
    runtime: '22d 14h',
    minInvestment: 500,
    trades24h: 12,
    totalTrades: 456,
    sharpeRatio: 2.1,
    aum: 10000,
    performanceData: [0, 1.2, 3.5, 5.8, 7.1, 8.0, 8.2],
    direction: 'Long',
    leverage: 1,
    status: 'active',
  },
  {
    id: '7',
    name: 'Trend Following Bot',
    type: 'Trend',
    marketPair: 'ETH/USDT',
    riskLevel: 'High',
    pnl30d: 18.7,
    pnlUSD: 1870.00,
    drawdown30d: 8.9,
    roi: 18.7,
    description: 'Advanced trend-following strategy with dynamic stop-loss',
    creator: 'AlgoMaster',
    creatorAvatar: 'AM',
    followers: 2156,
    isVerified: true,
    isMyStrategy: false,
    runtime: '8d 3h',
    minInvestment: 2000,
    trades24h: 8,
    totalTrades: 89,
    sharpeRatio: 3.2,
    aum: 10000,
    performanceData: [0, 5.2, 10.1, 14.8, 16.5, 17.9, 18.7],
    direction: 'Long',
    leverage: 3,
    status: 'active',
  },
  {
    id: '8',
    name: 'Custom Rebalancer',
    type: 'Rebalancing',
    marketPair: 'ETH/USDT',
    riskLevel: 'Medium',
    pnl30d: 6.4,
    pnlUSD: 640.00,
    drawdown30d: 3.2,
    roi: 6.4,
    description: 'Custom portfolio rebalancing workflow',
    creator: 'DeFiBuilder',
    creatorAvatar: 'DB',
    followers: 456,
    isVerified: false,
    isMyStrategy: false,
    runtime: '12d 5h',
    minInvestment: 1000,
    trades24h: 5,
    totalTrades: 67,
    sharpeRatio: 1.8,
    aum: 10000,
    performanceData: [0, 1.0, 2.5, 4.2, 5.5, 6.0, 6.4],
    direction: 'Neutral',
    leverage: 1,
    status: 'active',
  },
  {
    id: '9',
    name: 'Arbitrage Bot',
    type: 'Arbitrage',
    marketPair: 'ETH/USDT',
    riskLevel: 'Low',
    pnl30d: 4.5,
    pnlUSD: 450.00,
    drawdown30d: 0.8,
    roi: 4.5,
    description: 'Delta neutral strategy to earn Funding Fee effortlessly',
    creator: 'ArbKing',
    creatorAvatar: 'AK',
    followers: 1234,
    isVerified: true,
    isMyStrategy: false,
    runtime: '30d 0h',
    minInvestment: 10000,
    trades24h: 156,
    totalTrades: 4680,
    sharpeRatio: 4.1,
    aum: 10000,
    performanceData: [0, 0.8, 1.5, 2.5, 3.5, 4.2, 4.5],
    direction: 'Neutral',
    leverage: 1,
    status: 'active',
  },
];

// Export combined for backward compatibility
export const mockStrategies = [...mockMyStrategies, ...mockMarketplaceStrategies];
